---
title: "Day 30"
output: html_document
---
###[Day 0](http://xpontimus.github.io/gqday0.html)

###[Day 15](http://xpontimus.github.io/gqday15.html)

###[Day 30](http://xpontimus.github.io/gqday30.html)

###[Day 60](http://xpontimus.github.io/gqday60.html)

###[Day 90](http://xpontimus.github.io/gqday90.html)

##Data for Day 60. 
```{r setup, include=FALSE}
library(tidyr)
library(dplyr)
library(readr)
library(ggplot2)
library(readxl)
library(reshape2)

gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 5)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)

userlist <- as.character(factor(gamedata$Email))

```

```{r cars3, echo = FALSE}

gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating, stillgamefree)

cleaneddata <- na.omit(cleaneddata)

cleaneddata <- data.frame(lapply(cleaneddata[,2:16], mean))

scoreddata <- gather(cleaneddata, var, value, schoolworkcareer:globalrating)

gg <- ggplot(scoreddata, aes(x=var, y=value, fill=var))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(round(scoreddata$value, digits = 2)), hjust = 1)
gg <- gg + labs(x = "Survey Question", y = "Average Score", title = "Day 30 Average Score by Question")
gg <- gg + scale_y_continuous(limits = c(0, 7.5))
gg <- gg + scale_x_discrete(limits = scoreddata$var[order(scoreddata$value)])
gg <- gg + theme(legend.position = "none") 
gg <- gg + coord_flip()
gg
```

The graph above depicts the averages for each question for this day.

```{r withdraw, echo = FALSE}
tableddata <- data.frame(table(gamedata$stillgamefree))
gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "Still Game Free? - Day0")
gg <- gg + theme(legend.position = "none")
gg
```


Relapse Rate:
```{r relapse, echo = FALSE}
tableddata$Freq[1] / sum(tableddata$Freq) * 100
```


#DAY 30 Frequencies
The graphs below represent how many people (frequency) selected a particular answer to the survey for each question.
```{r freq3, echo = FALSE}
gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$schoolworkcareer))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "School/Work/Career - Day0")
gg <- gg + theme(legend.position = "none")
gg
summary(cleaneddata$schoolworkcareer)



gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$familyrelationships))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "School/Work/Career - Day 0")
gg <- gg + theme(legend.position = "none")
gg
summary(cleaneddata$familyrelationships)



gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$intimaterelationships))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "Intimate Relationships - Day 0")
gg <- gg + theme(legend.position = "none")
gg
summary(cleaneddata$intimaterelationships)



gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$relationshipswithothers))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "Relationships with Others - Day 0")
gg <- gg + theme(legend.position = "none")
gg
summary(cleaneddata$relationshipswithothers)



gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$yourfuture))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "Your Future - Day 0")
gg <- gg + theme(legend.position = "none")
gg
summary(cleaneddata$yourfuture)



gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$yourfeelings))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "Your Feelings - Day 0")
gg <- gg + theme(legend.position = "none")
gg
summary(cleaneddata$yourfeelings)



gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$yourappearance))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "Your Appearance- Day 0")
gg <- gg + theme(legend.position = "none")
gg
summary(cleaneddata$yourappearance)



gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$yourleisure))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "Your Leisure - Day 0")
gg <- gg + theme(legend.position = "none")
gg
summary(cleaneddata$yourleisure)



gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$yourvalusandbeliefs))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "Your Values and Beliefs - Day 0")
gg <- gg + theme(legend.position = "none")
gg
summary(cleaneddata$yourvalusandbeliefs)



gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$thinkingandconcentrating))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "Thinking and Concentrating - Day 0")
gg <- gg + theme(legend.position = "none")
gg
summary(cleaneddata$thinkingandconcentrating)



gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$generalphysicalhealth))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "General Physical Health - Day 0")
gg <- gg + theme(legend.position = "none")
gg
summary(cleaneddata$generalphysicalhealth)



gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$psychologicalhealth))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "Psychological Health - Day 0")
gg <- gg + theme(legend.position = "none")
gg
summary(cleaneddata$psychologicalhealth)



gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$healthrelatedtofoodandweight))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "Health Related to Food and Weight - Day 0")
gg <- gg + theme(legend.position = "none")
gg
summary(cleaneddata$healthrelatedtofoodandweight)



gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$timemanagement))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "Time Management - Day 0")
gg <- gg + theme(legend.position = "none")
gg
summary(cleaneddata$timemanagement)



gamedata <- read_excel("data/Gaming QoL Data2.xlsx", sheet = 3)
gamedata$Email <- tolower(gamedata$Email)
gamedata$Email <- gsub(" ", "", gamedata$Email)
colnames(gamedata) <- gsub("[^[:alnum:]]", "", tolower(colnames(gamedata)))

cleaneddata <- gamedata[gamedata$email %in% userlist,]

cleaneddata <- select(cleaneddata, email, schoolworkcareer, familyrelationships, intimaterelationships,
                      relationshipswithothers, yourfuture, yourfeelings, yourappearance,
                      yourleisure, yourvalusandbeliefs, thinkingandconcentrating, generalphysicalhealth,
                      psychologicalhealth, healthrelatedtofoodandweight, timemanagement, globalrating)

tableddata <- data.frame(table(cleaneddata$globalrating))

gg <- ggplot(tableddata, aes(x= Var1, y=Freq, fill = Var1))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + geom_text(label = as.character(tableddata$Freq), vjust = -.5)
gg <- gg + labs(x = "Survey Answer", y = "Frequency", title = "Global Rating - Day 0")
gg <- gg + theme(legend.position = "none")
gg

summary(cleaneddata$globalrating)
```